version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: leituras_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db_test:
    image: postgres:13
    container_name: postgres_db_test
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: leituras_db_test
    ports:
      - "5430:5432"
    volumes:
      - postgres_data_test:/var/lib/postgresql/data

  api:
    build: ./api
    container_name: api_container
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: leituras_db
      DB_PORT: 5432
    depends_on:
      - db
    volumes:
      - ./api:/app
      - /app/node_modules

volumes:
  postgres_data:
  postgres_data_test: